export const CENSOR_COURSES = 'CENSOR_COURSES'
export const CENSOR_COURSES_SUCCESS = 'CENSOR_COURSES_SUCCESS'
export const DELETE_COURSES = 'DELETE_COURSES'
export const DELETE_COURSES_SUCCESS = 'DELETE_COURSES_SUCCESS'
